# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0003_auto_20170430_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ManyToManyField(to='degrees.Course')),
            ],
        ),
    ]
